# name: Deploy Laravel 10 and React Frontend to InfinityFree

# on:
#   push:
#     branches:
#       - main  # Ez akkor fut le, amikor a "main" branch-ra történik push

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # 1. Checkout a repository
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # 2. Set up PHP (Laravel backendhez)
#       - name: Set up PHP
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: '8.1'  # Használhatod a szükséges PHP verziót
#           extensions: mbstring, bcmath, zip, curl

#       # 3. Laravel composer telepítés
#       - name: Install Composer 2.5.5
#         run: |
#           curl -sS https://getcomposer.org/installer | php -- --version=2.5.5
#           sudo mv composer.phar /usr/local/bin/composer  # Mozdítsd a fájlt globálisan elérhető helyre
#           composer update
#           composer install  # Telepíti a függőségeket
#           composer --version  # Ellenőrzi a telepített Composer verzióját

#       # 4. Laravel beállítások (kulcs generálás, cache)
#       - name: Configure Laravel backend
#         run: |
#           php artisan key:generate
#           php artisan config:cache
#           php artisan route:cache
#           php artisan view:cache

#       # 5. React frontend build
#       - name: Install Node.js and Build React frontend
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'  # Használhatod a szükséges Node verziót
#       - run: |
#           npm install
#           npm run build  # Ezzel készítjük el a React build fájlokat

#       # 6. FTP deploy Laravel backend
#       - name: Deploy Laravel backend to FTP
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.5
#         with:
#           server: ${{ secrets.FTP_HOST }}
#           username: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           local-dir: ./  # Az egész Laravel projektet feltöltjük
#           server-dir: ${{ secrets.FTP_REMOTE_LARAVEL_PATH }}  # A távoli mappa a Laravel számára

name: FTP Deploy

on:
  push:
    branches:
      - main  # Az a branch, amelyről deploy-olni szeretnél

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up FTP deployment
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}  # Az FTP szerver címe
          username: ${{ secrets.FTP_USERNAME }}  # Az FTP felhasználónév
          password: ${{ secrets.FTP_PASSWORD }}  # Az FTP jelszó
          local-dir: ./  # A helyi mappa, amit fel szeretnél tölteni
          server-dir: /cigand_2025/  # A szerver mappa, ahová tölteni szeretnéd
          git-ftp-args: --syncroot --timeout 600  # Timeout növelése

